backend:
  name: github
  branch: blog
  repo: deepettas/deepettas.github.io

media_folder: "src/assets/images"
public_folder: "static/images"

collections:
  - name: "about"
    label: "About"
    folder: "content/about"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "index", name: "index", widget: "integer" }
      - { label: "published", name: "published", default: true, widget: "select", options: [true, false]}
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "date" }
      - { label: "section", name: "section", widget: "string" }
      - { label: "description", name: "description", widget: "string" }

  # - name: "data"
  #   label: "Data"
  #   files:
  #     - name: "about"
  #       label: "About"
  #       file: "src/data/About.yml"
  #       fields:
  #         - { label: "Title", name: "title", widget: "string", default: "About" }
  #         - name: "items"
  #           label: "Items"
  #           widget: "list"
  #           fields:
  #             - { label: "Title", name: "title", widget: "string" }
  #             - { label: "Description", name: "description", widget: "text" }

